# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookLoginExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacebookLoginExample
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKShareKit'
  # pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  
end
